name: sliceofgourmet
description: Flutter app for Slice Of Gourmet, recipes from WordPress
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  http: ^1.2.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  html: ^0.15.4
  google_sign_in: ^6.2.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TASAExplorer
      fonts:
        - asset: assets/fonts/TASAExplorer-Regular.ttf
          weight: 400
        - asset: assets/fonts/TASAExplorer-Medium.ttf
          weight: 500
        - asset: assets/fonts/TASAExplorer-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TASAExplorer-Bold.ttf
          weight: 700
        - asset: assets/fonts/TASAExplorer-ExtraBold.ttf
          weight: 800
